name: ghcdoc

dependencies:
                - base
                - containers
                - lens


license: BSD3
executables:
        ghcdoc:
                main: main.hs
                dependencies:
                        - ghcdoc

library:
        source-dirs:
                - src
        exposed-modules:
                Server
                HttpClient
        other-modules:
                Paths_ghcdoc
        dependencies:
                - binary
                - bytestring-trie
                - regex-applicative
                - bytestring
                - Cabal
                - cmdargs
                - ghc-paths
                - edit-distance
                - filepath
                - Glob
                - process
                - process-extras
                - split
                - text
                - unix
                - zstd
                - directory
                - happstack-server
                - blaze-html
                - tagsoup
                - HTTP
                - network-uri
                - transformers


tests:
        webdriver:
                main: test.hs
                dependencies:
                        - hspec
                        - hspec-webdriver
                        - process
                        - webdriver
                        - ghcdoc
