{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE ViewPatterns #-}
{-# HLINT ignore "Eta reduce" #-}
{-# OPTIONS_GHC -Wno-typed-holes #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}
{-# OPTIONS_GHC -w #-}

-- | https://github.com/ocaml/merlin/blob/master/doc/features.md
--
-- parse haddock .txt files done in ParseHoogle
-- try parsing ghci's :info TFName -- done in the badly named ParseHoogle
--
-- hoogle .txt files don't even have type instances so should I use hie files?
-- https://github.com/haskell/cabal/issues/8685 is closed and the fixing changelog
-- as of Aug 2023:
--
-- Hie files generated by GHC are now stored in the `extra-compilation-artifacts`
-- directory which gets installed with the package.
--
-- Each declaration makes an edge in a graph (which can have cycles).
-- Unification-fd will take care of type variables? Maybe it's more of an academic problem
module Search (module Search) where

import Control.Lens
import Control.Lens.Unsound (adjoin, lensProduct)
import Control.Monad
import Control.Monad.Logic
import Control.Monad.Trans.Class
import Control.Monad.Trans.Except
import Control.Monad.Trans.Maybe
import Control.Monad.Trans.Reader
import Control.Monad.Trans.State (State, StateT (runStateT), evalState, evalStateT, execStateT, get, put, runState)
import Control.Monad.Trans.State.Lazy (execState)
import Control.Monad.Trans.Writer
import Control.Unification
import Control.Unification.IntVar
import Control.Unification.Types
import Data.Char
import Data.Data
import Data.Data.Lens
import Data.Either
import Data.Foldable
import Data.Functor.Foldable
import Data.Functor.Foldable.TH (makeBaseFunctor)
import Data.Generics hiding (Generic)
import Data.IntMap (IntMap)
import qualified Data.IntMap as IM
import Data.List
import Data.Map (Map)
import qualified Data.Map as M
import Data.Set (Set)
import qualified Data.Set as S
import qualified Data.Set as Set
import qualified Data.Set.Lens as S
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as T
import Debug.Trace
import GHC.Generics hiding (to)
import Language.LBNF (ParseMonad (..))
import ParseHoogle
import ParseQuery hiding (Name (..))
import qualified ParseQuery
import System.Process (system)
import Text.Show.Pretty (pPrint)

data Search = Search
  { _abstract :: [Typ],
    _query :: [NameQ]
    -- db :: [Dec]
  }

-- * unification-fd adapter

makeBaseFunctor ''Typ

deriving instance Data IntVar

deriving instance Data (UTerm TypF IntVar)

deriving instance Data (TypF (UTerm TypF IntVar))

deriving instance Generic1 TypF

instance Unifiable TypF

instance Unifiable []

-- | Convert 'Typ' from BNFC-meta into one suitable for unification-fd.
-- All type variables with the same name are represented by 'freeVar'.
--
-- > do
-- > (a,b,c) <- toUTerm (a,b,c)
-- > Identity x <- toUTerm (Identity x)
--
-- But is this right? The `M` keeps state so that freeVar added with `x` will
-- not overlap those with `(a,b,c)`
--
-- By preapplying the fromUTermEnv, I lose the opportunity to save the old variable names.
-- Why not store it in M? Where do I put the WriterT (IntMap String). It ought to commute with
-- intvarbindingT.
--
-- I am converting type signatures parsed by bnfc-meta into a form for
-- unification-fd. I have a `toUTerm :: Each s t Typ (UTerm TypF IntVar) => s
-- -> M t`. I have success with `do (a,b) <- toUTerm (a,b); c <- toUTerm c;
-- ...`, but can it also be made to work if instead the input `b` becomes `bs
-- :: [Typ]`? If I had `tinplate :: (Data a, Typeable a) => Traversal' s a`
-- except as a `Traversal s t a b` I would use that instead of `each`. There is
-- a `Map String IntVar` that is new for every `toUTerm`. If I store that Map
-- in M, I will end up with `do a <- toUTerm a; bs <- toUTerm bs; resetVarMap;
-- c <- c; ...` . But `do ~(a:bs) <- toUTerm (a:bs); c <- toUTerm c` looks the
-- best so far.
--
-- Assumes type variables have been renamed to avoid shadowing
toUTerm :: (Each s t Typ (UTerm TypF IntVar)) => s -> M t
toUTerm typs = do
  (s', m) <- each toUTerm1 typs `runStateT` (mempty :: Map String IntVar)
  lift $ lift $ tell $ toIM m
  return s'
  where
    toIM :: Map String IntVar -> IntMap String
    toIM m = IM.fromList [(i, s) | (s, IntVar i) <- M.toList m]

    toUTerm1 = \case
      Iden (Name name@(x : _)) | isLower x -> do
        let newN = do
              v <- lift $ lift freeVar
              at name ?= v
              return v
        n <- maybe newN return =<< use (at name)
        return $ UVar n
      x -> UTerm <$> traverse toUTerm1 (project x)

fromUTermEnv ::
  -- | original names
  IntMap String ->
  UTerm TypF IntVar ->
  Typ
fromUTermEnv originalNames typ = fromUTerm1 typ
  where
    fromUTerm1 = \case
      UVar n -> Iden (Name (uniquePrefix ++ show n))
      UTerm f -> undefined f

    -- "a" or "z0_", whatever doesn't occur in the whole type
    uniquePrefix =
      let allNames = typ ^.. uniplate . nameF <&> \(Name x) -> x
          candidateNames =
            map (: []) ['a' .. 'z']
              ++ [c : show n ++ "_" | c <- ['a' .. 'z'], n <- [0 ..]]
       in head $ filter (`notElem` allNames) candidateNames

    nameF :: Traversal' (UTerm TypF IntVar) Name
    nameF = biplate

-- where do I put LogicT
type M = ExceptT (UFailure TypF IntVar) (IntBindingT TypF (WriterT (IntMap String) Logic))

-- continues https://ro-che.info/articles/2017-06-17-generic-unification
-- runM :: Int -> M a -> (Either (UFailure TypF IntVar) a, IntMap String)
runM n = observeMany n . runWriterT . evalIntBindingT . runExceptT

-- | `[(String, [Name], [(String, Typ)])]` from 'dataTable'
--
-- >  , [ ( "Either"
-- >     , [ Name "a" , Name "b" ]
-- >     , [ ( "Left"
-- >         , Sym
-- >             (Iden (Name "a"))
-- >             (NormalSym (Symb "->"))
-- >             (App
-- >                (App (Iden (Name "Either")) (Iden (Name "a"))) (Iden (Name "b")))
-- >         )
-- >       , ( "Right"
-- >         , Sym
-- >             (Iden (Name "b"))
-- >             (NormalSym (Symb "->"))
-- >             (App
-- >                (App (Iden (Name "Either")) (Iden (Name "a"))) (Iden (Name "b")))
-- >         )
-- >       ]
--
-- Somehow this is going to be useful for deciding what is available or required
-- when there is an Either in a function type signature.
type DataTable = [(String, [Name], [(String, Typ)])]

-- | `[([(String, [Typ])], Typ, String, Int)]` from 'instanceTable'
type InstanceTable = [([(String, [Typ])], Typ, String, Int)]

resolve ::
  DataTable ->
  InstanceTable ->
  [Typ] ->
  Typ ->
  NameQ ->
  [(Either (UFailure TypF IntVar) a, IntMap String)]
resolve dtab itab cxt ty NameQ {pol, name} = runM 5 do
  Identity qTy <- toUTerm $ Identity $ Iden (Name name)

  -- concrete and variable types with polarity
  let (conPols, typPols) = getVarPolTyp ty ^.. vpMap & partitionEithers

  -- convert all Typ to UTerm TypF IntVar
  ~(ty : fstTypPols_cxt) <- toUTerm (ty : map fst typPols ++ cxt)
  typPols <- return $ zip fstTypPols_cxt (map snd typPols)
  let cxt = drop (length typPols) fstTypPols_cxt

  -- attempt to unify qTy with typPols
  -- use a binding monad which supports backtracking in order to undo the changes
  (t, p) <- lift $ asum $ map return typPols
  lift $ guard $ undefined name pol
  matches <- t <:= qTy
  lift $ guard matches
  -- so much lift I could change the monad to a newtype and then
  -- derive the instances MonadFail so that
  -- True <- t <:= qTy
  -- maybe it is not really possible

  {-
  if ty is
  Int -> T b -> a

  tyVP =
      [ ( Left "Int"
     , fromList [ False ])
   , ( Left "a"
     ,  fromList [ True ])
     )
   , ( Right (App (Iden (Name "T")) (Iden (Name "b")))
     ,fromList [ False ] )
     )
   ]

  so then "Int" needs to be selected based on "q"
  and an attempt has to be made to unify "a" with whatever is in q
  premature optimization by seeing how to turn "a" into something
  concrete. Maybe for some particular types concrete 0 parameter types
  this makes sense. So I would need to stop as soon as they keys in the
  map stop being Int, Char etc. the result type isn't clear either --
  same as vpdMap1s
  it is overwhelming to have such a big function but I need so much context

  -}
  -- I am really prepared?
  return undefined

-- | like dataCons except for classes
--
-- > instance (Num a, Num b) => Num (a,b)
--
-- becomes
--
-- [ ( [ ( "Num" , [ Iden (Name "b") ] )
--      , ( "Num" , [ Iden (Name "a") ] )
--      ]
--    , Tup (Iden (Name "a")) (Iden (Name "b"))
--    , "Num"
--    , 1
--    )
--  ]
--
-- ie. the result type could become a data
--
-- > [([(String, [Typ])], -- context
-- >         Typ, -- "pattern"
-- >         String, -- class name
-- >         Int)] -- which pattern (2 for the 2nd parameter in a MultiParamTypeClasses)
--
-- > instance C Int
-- > instance C a => D a
-- > f :: D a => a
--
-- gives
--
-- [ [ ( [] , Iden (Name "Int") , "C" , 1 ) ]
-- , [ ( [ ( "C" , [ Iden (Name "a") ] ) ]
--    , Iden (Name "a")
--    , "D"
--    , 1
--    )
--  ]
--
-- now I want to find `f` with the `Int+` query
-- from Int+ I get the first instance, from the "C" 1 I get the next instance. But I also need
-- to unify Iden (Name "a") with Iden (Name "Int"). Find the subsitution that turns "a" into "Int".
--
-- It is unclear whether I store D Int
--
-- am I wrong in treating MPTCS as an int-indexed class? That is C a b is no
-- different than C1 a and C2 b. This introduces errors that expand the list of
-- found instances, since `C a b`
-- becomes `C1 a` `C2 b` and will confabulate the existence of `C A B` given only
-- `C A A` and `C B B` exist. Still, the extra imagined instances probably may not
-- be too much of an annoyance.
--
-- ( [] , Iden (Name "Int") , "C" , 1 )
instanceTable :: Dec -> InstanceTable
instanceTable (Inst (Sym cxt (NormalSym (Symb "=>")) x)) =
  instanceTable (Inst x)
    <&> _1 .~ map splitInstHead (split cxt)
  where
    split (Tup a b) = b : split a
    split x = [x]
instanceTable (Inst (splitInstHead -> (n, ts))) = [([], t, n, i) | (t, i) <- zip ts [1 ..]]
-- moved to dataTable
-- instanceTable (Fam FamTy (splitInstHead -> (n, ts)) rhs)
--   = [ ([("xxx", [rhs])], t, n, i) | (t, i) <- zip ts [1 .. ] ]
-- instanceTable (FamF _ (splitInstHead -> (n, ts))) = [ ([], t, n, i) | (t, i) <- zip ts [1 .. ] ]
-- instanceTable (Newty x) = ...
-- instanceTable (Ty x) = ...
-- instanceTable (Dat x) = ...
-- instanceTable (Fam _ (splitInstHead -> (n, ts)) rhs) = [ ([], t, n, i) | (t, i) <- zip ts [1 .. ] ]
-- type InstanceTable = [([(String, [Typ])], Typ, String, Int)]
-- type instance F a b = rhs
-- n = F
-- ts = [a,b]
-- instance Cxt => C a b
-- somehow rhs will go into the _1? Or do I have it backwards and instead lhs
-- goes into the _1 and rhs goes into the t,n,i? I know they are different, but
-- still each construction leads to a kind of edge in a graph.
instanceTable _ = []

-- | Extract data constructors
--
-- when used together with cleanLeadingHasType and parseHoogleFile
--
-- > data Ty
-- > Con1 :: Int -> Ty
-- > Con2 :: Char -> Ty
--
-- Becomes:
--
-- > [ ( "Ty"
-- >   , []
-- >   , [ ( "Con1"
-- >       , Sym (Iden (Name "Int")) (Symb "->") (Iden (Name "Ty"))
-- >       )
-- >     , ( "Con2"
-- >       , Sym (Iden (Name "Char")) (Symb "->") (Iden (Name "Ty"))
-- >       )
-- >     ]
-- >   )
-- > ]
dataTable :: [Dec] -> DataTable
dataTable decs = dataTable1 decs -- & mapped . _3 . mapped . _2 %~ splitArrs

-- `a -> b -> c d` becomes [a,b,c d]
-- why shouldn't it be `g` instead?
splitArrs :: Typ -> [Typ]
splitArrs = \case
  Sym a (NormalSym (Symb "->")) c -> a : splitArrs c
  x -> [x]

dataTable1 (DatE (Name n : ps) : (spanExps n -> (es, rest))) = (n, ps, es) : dataTable1 rest
dataTable1 (Dat (Name n : ps) (NormalCons cs) : rest) = (n, ps, map f cs) : dataTable1 rest
  where
    f :: DataCon -> (String, Typ)
    f (Con (Name nc) ts) = (nc, foldr (\x xs -> Sym x (NormalSym (Symb "->")) xs) conT ts)
    conT = foldl App (Iden (Name n)) (map Iden ps)
dataTable1 (Fam _ r@(splitInstHead -> (n, pst)) z : rest) = (n, ps, [e]) : dataTable1 rest
  where
    ps :: [Name]
    ps =
      pst
        ^.. template
          . filtered
            ( \case
                Name (x : _) -> isLower x
                _ -> False
            )
    e :: (String, Typ)
    e = case splitInstHead z of
      (x, xs) -> (x, arrT xs r)

    -- arrT [a,b,c] d = a -> b -> c -> d
    arrT :: [Typ] -> Typ -> Typ
    arrT = flip $ foldr (\x xs -> Sym x (NormalSym (Symb "->")) xs)
dataTable1 (DatI p1 (Symb n) p2 : (spanExps n -> (es, rest))) = (n, [p1, p2], es) : dataTable1 rest
dataTable1 (_ : xs) = dataTable1 xs
dataTable1 _ = []

spanExps :: String -> [Dec] -> ([(String, Typ)], [Dec])
spanExps c (Exp (Fun [Name n] bo) : xs) | all isUpper (take 1 n) = spanExps c xs & _1 %~ ((n, bo) :)
spanExps c (Exp (FunI (Symb a) bo) : xs) | all (== ':') (take 1 a) = spanExps c xs & _1 %~ ((a, bo) :)
spanExps _ xs = ([], xs)

-- how to collect the cxt?
-- I have to make a kind of environment
-- where do I start from?
-- I start at the instance heads that have no type variables
-- data definitions are the same thing with respect to searches
-- except the syntax is different. That is,
--
-- data D = D E F
-- f :: D -> E
--
-- f should be found for -E, because D necessarily contains an E
--
-- likewise:
--
-- class C a
-- instance C E
-- g :: C a => a
--
-- g should be found for +E, because C sometimes contains an E
--
-- I only need to treat each variable separately:
--
-- instance C F
-- h :: C a => a
--
-- h should be found for "+F +E" even though we cannot have the `a` type variable
-- be both at the same time.
--
-- so classes and data and type families are all the same? They are a mapping from
-- one name to many (possible). If I start at the functions, it doesn't necessarily
-- stop:
-- instance (C a, C b) => C (a,b)
-- i :: C a => a
--
-- now I contains E, (E,E), ((E,E),E) etc.
--
-- so if I am searching for E, I can't split the search into two parts,
-- where the first generates all of the possible types and the second
-- searches among them. The two steps have to be interleaved, and somehow
-- such a substitution can't go on forever. UndecidableInstances guarantees
-- that a search for instances stops, but in my case it I don't need be sure
-- that the instance context is satisfied.
--
-- DE-9IM is an example of a language to describe the relation between spatial
-- sets. Parametrized types aren't spatial, though "subsumes" and "contains" might
-- not have a meaningful difference. unification-fd only solves the question of
-- are these two parameterized types similar. It doesn't solve the question of
-- looking up the Left and Right constructors when deciding if

splitInstHead :: Typ -> (String, [Typ])
splitInstHead = go []
  where
    go accum (App a b) = go (b : accum) a
    go accum (Iden (Name x)) = (x, accum)
    go accum (Sym a (SymBT (Name x)) b) = (x, a : b : accum)
    go x y = error $ show (x, y)

atsList :: ATS -> [(Typ, String, Int)]
atsList NoATS = []
atsList (ATS xs) = concatMap atList xs

atList :: AT -> [(Typ, String, Int)]
atList = undefined

-- ghcid --warnings --command 'cabal repl' -TSearch.main --reload test.txt
main = do
  -- system "hs2pdf src/Search.hs"
  pf <- cleanLeadingHasType . rights <$> parseHoogleFile "test.txt"
  let it = concatMap instanceTable $ concatMap (\(Decs x) -> x) pf
  pPrint ("IT", it)

  let dt = dataTable $ concatMap (\(Decs x) -> x) pf
  pPrint ("DT", dt)

  (cx, vpdM) : _ <-
    M.toList . vpdMap1s . cleanLeadingHasType . snd . partitionEithers
      <$> parseHoogleFile "test.txt"
  pPrint ("vpdM", cx, vpdM)
  let Ok q = parseNameQS "Int"
  pPrint ("q", q)

  let dropRights :: (Ord a) => M.Map (Either a b) x -> M.Map a x
      dropRights xs = M.fromList [(b, x) | (Left b, x) <- M.toList xs]

  -- seems okay for concrete types
  pPrint ("lookupQS:", lookupQS q $ dropRights vpdM)

-- testing unification-fd
-- IntBindingState

{- vpdM ends up with a:
, ( Left "a"
  , fromList [ ( fromList [ True ] , fromList [ "e" ] ) ]

I need to retain the D a =>

  -}

lookupQS :: (Ord a) => [NameQ] -> Map String (Map (Set Bool) (Set a)) -> Set a
lookupQS ns vpd =
  foldl (\result n -> lookupQ n vpd result) full $
    sortOn isNeg ns -- negatives last
  where
    full = S.unions $ vpd ^.. folded . folded
    isNeg (NameQ _ _ (Just (_, S.toList -> [x]))) = x
    isNeg _ = False

lookupQ ::
  (Ord a) =>
  -- | a single word like +A-
  NameQ ->
  Map String (Map (Set Bool) (Set a)) ->
  -- | modification of the result set
  (Set a -> Set a)
lookupQ NameQ {pol, name, pres} vpd = presOp pres $ S.unions (vpd ^.. ix name . polOp pol)

polOp :: Maybe (Bool, Set Bool) -> Traversal' (Map (Set Bool) (Set a)) (Set a)
polOp Nothing = traversed
polOp (Just nb) = itraversed . ifiltered (\i _ -> keep nb i)
  where
    keep :: (Bool, Set Bool) -> Set Bool -> Bool
    keep (True, q) b = q == b
    keep (False, q) b = not (S.null (q `S.intersection` b)) -- or setIsSubsetOf?

presOp :: (Ord a) => Maybe (Bool, Set Bool) -> (Set a -> Set a -> Set a)
presOp = \case
  Nothing -> S.intersection
  Just (_, S.toList -> [True]) -> (<>) -- not really useful but what else could the trailing + mean?
  Just (_, S.toList -> [False]) -> flip (S.\\)
  pm -> error $ "cannot interpret " ++ show pm ++ " as a set operation"

-- TODO Control.Applicative.Lift.Errors for lookupQS, or maybe it's Writer
-- (Seq String) for warnings only

-- | VarPol is the core of the search. 'getVarPolDec' or 'getVarPolTyp' produce it.
--
-- the traversal 'g' collects this state. True and False are + and - polarities.
-- Set Typ holds class constraints which were anywhere in the signature.
newtype VarPol = VarPol (Map String (Set Bool), Map Typ (Set Bool), Set Typ)
  deriving (Show, Monoid, Semigroup, Generic)

instance Wrapped VarPol

instance (t ~ VarPol) => Rewrapped VarPol t

cleanLeadingHasType input =
  everywhere
    ( mkT \case
        App HasType x -> x
        x -> x
    )
    input

-- | Make a map to function names
vpdMap1s ::
  [Decs] ->
  Map
    (Set Typ) -- context (class constraints) for type variables in Right
    ( Map
        (Either String Typ) -- Left "Int"
        -- or Right (App (Iden (Name "T")) (Iden (Name "b")))
        ( Map
            (Set Bool) -- polarity
            (Set String) -- function names
        )
    )
vpdMap1s = M.unionsWith (M.unionWith (M.unionWith S.union)) . concatMap vpdMap1

-- > e :: D a => Int -> T b -> a
--
-- produces a
--
-- >    [ App (Iden (Name "D")) (Iden (Name "a")) ]
-- >      , fromList
-- >          [ ( Left "Int"
-- >            , fromList [ ( fromList [ False ] , fromList [ "e" ] ) ]
-- >            )
-- >          , ( Left "a"
-- >            , fromList [ ( fromList [ True ] , fromList [ "e" ] ) ]
-- >            )
-- >          , ( Right (App (Iden (Name "T")) (Iden (Name "b")))
-- >            , fromList [ ( fromList [ False ] , fromList [ "e" ] ) ]
-- >            )
-- >          ]
-- >      )
--
-- clearly Int and T b have nothing to do with the context
-- `T a` or `a` do.
vpdMap1 x@(Decs xs) =
  [ M.singleton (shrinkCxt v cxt) $
      M.singleton v $
        M.singleton polarities $
          S.singleton d
    | x <- xs,
      (Just d, vp@(VarPol (_, _, cxt))) <- [getVarPolDec x],
      (v, polarities) <- vp ^.. vpMap . collectSnd
      -- here I have to filter out the types that have nothing to do with the context
      -- I have to shrink the context
  ]

-- | shrink the context excessively. That is,
--
-- > f :: (C a b, b ~ B) => a -> b
--
-- > shrinkCxt (Left "a") [C a b, b ~ B] ==> [C a b]
-- > shrinkCxt (Left "b") [C a b, b ~ B] ==> [C a b, b ~ B]
--
-- so eventually `f` may end up coming up in a search result
-- for a concrete A but there is no `C A B`. This is not wrong
-- maybe it prompts the user to write `instance C A B`
--
-- Type level strings are not treated properly, but I have to
-- add them to the parser first.
shrinkCxt :: Either String Typ -> Set Typ -> Set Typ
shrinkCxt (Left n) = S.filter (has (template . filtered (== n)))
shrinkCxt (Right t) = S.filter (has (template . filtered (`elem` tn)))
  where
    tn :: [String]
    tn = t ^.. template

-- | 'adjoin' except include indices
iadjoinish ::
  AnIndexedTraversal' i s a ->
  AnIndexedTraversal' j s b ->
  Lens' s [Either (i, a) (j, b)]
iadjoinish l1 l2 f x =
  f
    ( (x ^@.. cloneIndexedTraversal l1 <&> Left)
        <> (x ^@.. cloneIndexedTraversal l2 <&> Right)
    )
    <&> \ys ->
      x
        & partsOf (cloneIndexedTraversal l1) .~ map snd (lefts ys)
        & partsOf (cloneIndexedTraversal l2) .~ map snd (rights ys)

vpMap :: Traversal' VarPol (Either (String, Set Bool) (Typ, Set Bool))
vpMap =
  _Wrapped
    . ((_1 . itraversed) `iadjoinish` (_2 . itraversed))
    . traversed

-- vaguely Data.Profunctor.Strong.first' :: p a b -> p (a, c) (b, c)
collectSnd :: Iso' (Either (a, x) (b, x)) (Either a b, x)
collectSnd =
  iso
    ( \case
        Left (a, x) -> (Left a, x)
        Right (b, x) -> (Right b, x)
    )
    ( \case
        (Left a, x) -> Left (a, x)
        (Right b, x) -> Right (b, x)
    )

-- | `getVarPolDec "f :: A -> B"` produces (Just "f", vp)
--
-- where vp makes it easy to find "f" given A- or B+
getVarPolDec :: Dec -> (Maybe String, VarPol)
getVarPolDec dec =
  case dec of
    (Exp (Fun [Name n] ty)) -> do
      g $ removeForalls ty
      return (Just n)
    _ -> return Nothing
    `runReaderT` True
    `runState` mempty

{-
(Clas typ ats) -> return ()
(Pkg na) -> return ()
(Ver na) -> return ()
(Mod na) -> _wg
(Dat nas) -> _wh
(Inst typ) -> _wi
(Newty typ) -> _wj
(Ty typ) -> _wk
-}

getVarPolTyp :: Typ -> VarPol
getVarPolTyp typ = g (removeForalls typ) `runReaderT` True `execState` mempty

-- | ghci renames shadowed variables. This replaces
-- `forall x y z. e` with just `e`, no matter where it occurs.
-- There seems to be no need to care about RankNTypes when searching.
removeForalls :: Typ -> Typ
removeForalls = rewriteOf uniplate \case
  App x y | has forallBinding x -> Just y
  _ -> Nothing

-- | convert between `forall a b c.` and `["a","b","c"]` (actually reversed?)
forallBinding :: Prism' Typ [Name]
forallBinding = prism' inj ej
  where
    ej (App x Dot) = ej1 x
    ej _ = Nothing
    ej1 (Iden (Name "forall")) = Just []
    ej1 (App x (Iden n)) = (n :) <$> ej1 x
    ej1 _ = Nothing

    inj xs = foldl (\e x -> App e (Iden x)) (Iden (Name "forall")) xs `App` Dot

-- | classifies `Iden` polarities and also collects class constraints
-- perhaps two traversals would have been simpler
-- I am going to skip the -XNoFlexibleContexts version, so the constraints are
-- not collected in the right format
g :: Typ -> ReaderT Bool (State VarPol) ()
g (Iden (Name na)) = do
  p <- ask
  _Wrapped . _1 . at na <>= Just (Set.singleton p)
g (ListOf typ') = g typ'
g (App (Sym1 (Symb "->")) typ2) = local not $ g typ2
-- g (App typ' typ2) = g typ' >> g typ2 -- original
g axy@App {} = do
  p <- ask
  _Wrapped . _2 . at axy <>= Just (Set.singleton p)
g (Tup typ' typ2) = g typ' >> g typ2
g (Sym typ' (NormalSym (Symb "->")) typ2) = local not (g typ') >> g typ2
g (Sym cxts (NormalSym (Symb "=>")) typ2) = do
  sequence_
    [ _Wrapped . _3 <>= S.singleton cxt
      | cxt <- tupListRev cxts
    ]
  g typ2
g (Sym typ' op typ2) = g typ' >> g typ2
g (Sym1 sy) = return ()
g Unit = return ()
g EList = return ()
g (Bang typ') = g typ'
g Dot = return ()
g HasType = return ()
g Unpack = return ()
g (LitT s) = return ()
g (LitTN n) = return ()

appsListRev :: Typ -> [Typ]
appsListRev (App x y) = y : appsListRev x
appsListRev x = [x]

tupListRev :: Typ -> [Typ]
tupListRev (Tup x y) = y : tupListRev x
tupListRev x = [x]
