{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE ViewPatterns #-}
{-# HLINT ignore "Eta reduce" #-}
{-# OPTIONS_GHC -Wno-typed-holes #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}
{-# OPTIONS_GHC -w #-}

-- | https://github.com/ocaml/merlin/blob/master/doc/features.md
--
-- parse haddock .txt files done in ParseHoogle
-- try parsing ghci's :info TFName -- done in the badly named ParseHoogle
--
-- hoogle .txt files don't even have type instances so should I use hie files?
-- https://github.com/haskell/cabal/issues/8685 is closed and the fixing changelog
-- as of Aug 2023:
--
-- Hie files generated by GHC are now stored in the `extra-compilation-artifacts`
-- directory which gets installed with the package.
--
-- Each declaration makes an edge in a graph (which can have cycles).
-- Unification-fd will take care of type variables? Maybe it's more of an academic problem
module Search (module Search) where

import ParseHoogle
import Search.FromHoogle
import Search.LensExtra
import Search.UTerm
import Query hiding (Name (..))

import Text.Show.Pretty
import Control.Lens
import Control.Monad
import Control.Monad.Trans.Class
import Data.Either
import Data.Foldable
import Data.IntMap (IntMap)
import Data.List
import Data.Map (Map)
import Data.Set (Set)
import qualified Data.Set as S
import Data.Text (Text)
import Language.LBNF (ParseMonad (..))
import qualified Data.Map as M
import System.Process (system)

data Search = Search
  { _abstract :: [Typ],
    _query :: [NameQ]
    -- db :: [Dec]
  }

resolve ::
  Tables ->
  [Typ] ->
  Typ ->
  NameQ ->
  [(Either (UFailure TypF IntVar) a, IntMap String)]
resolve (Tables dtab itab _) cxt ty NameQ {pol, name, pres} = runM 5 do
  Identity qTy <- toUTerm $ Identity $ Iden (Name name)

  -- concrete and variable types with polarity
  let (conPols, typPols) = getVarPolTyp ty ^.. vpMap & partitionEithers

  -- convert all Typ to UTerm TypF IntVar
  ~(ty : fstTypPols_cxt) <- toUTerm (ty : map fst typPols ++ cxt)
  typPols <- return $ zip fstTypPols_cxt (map snd typPols)
  let cxt = drop (length typPols) fstTypPols_cxt

  -- attempt to unify qTy with typPols
  -- use a binding monad which supports backtracking in order to undo the changes
  (t, p) <- lift $ asum $ map return typPols
  lift $ guard $ undefined name pol
  matches <- t <:= qTy
  lift $ guard matches
  -- so much lift I could change the monad to a newtype and then
  -- derive the instances MonadFail so that
  -- True <- t <:= qTy
  -- maybe it is not really possible

  {-
  if ty is
  Int -> T b -> a

  tyVP =
      [ ( Left "Int"
     , fromList [ False ])
   , ( Left "a"
     ,  fromList [ True ])
     )
   , ( Right (App (Iden (Name "T")) (Iden (Name "b")))
     ,fromList [ False ] )
     )
   ]

  so then "Int" needs to be selected based on "q"
  and an attempt has to be made to unify "a" with whatever is in q
  premature optimization by seeing how to turn "a" into something
  concrete. Maybe for some particular types concrete 0 parameter types
  this makes sense. So I would need to stop as soon as they keys in the
  map stop being Int, Char etc. the result type isn't clear either --
  same as vpdMap1s
  it is overwhelming to have such a big function but I need so much context

  -}
  -- I am really prepared?
  return undefined


-- how to collect the cxt?
-- I have to make a kind of environment
-- where do I start from?
-- I start at the instance heads that have no type variables
-- data definitions are the same thing with respect to searches
-- except the syntax is different. That is,
--
-- data D = D E F
-- f :: D -> E
--
-- f should be found for -E, because D necessarily contains an E
--
-- likewise:
--
-- class C a
-- instance C E
-- g :: C a => a
--
-- g should be found for +E, because C sometimes contains an E
--
-- I only need to treat each variable separately:
--
-- instance C F
-- h :: C a => a
--
-- h should be found for "+F +E" even though we cannot have the `a` type variable
-- be both at the same time.
--
-- so classes and data and type families are all the same? They are a mapping from
-- one name to many (possible). If I start at the functions, it doesn't necessarily
-- stop:
-- instance (C a, C b) => C (a,b)
-- i :: C a => a
--
-- now I contains E, (E,E), ((E,E),E) etc.
--
-- so if I am searching for E, I can't split the search into two parts,
-- where the first generates all of the possible types and the second
-- searches among them. The two steps have to be interleaved, and somehow
-- such a substitution can't go on forever. UndecidableInstances guarantees
-- that a search for instances stops, but in my case it I don't need be sure
-- that the instance context is satisfied.
--
-- DE-9IM is an example of a language to describe the relation between spatial
-- sets. Parametrized types aren't spatial, though "subsumes" and "contains" might
-- not have a meaningful difference. unification-fd only solves the question of
-- are these two parameterized types similar. It doesn't solve the question of
-- looking up the Left and Right constructors when deciding if


-- ghcid --warnings --command 'cabal repl' -TSearch.main --reload test.txt
main = do
  -- system "hs2pdf src/Search.hs"
  Tables dt it (M.toList -> (cx, vpdM):_) <- makeTables <$> parseHoogleFile "test.txt"
  pPrint ("IT", it)
  pPrint ("DT", dt)
  pPrint ("vpdM", cx, vpdM)
  let Ok q = parseNameQS "Int"
  pPrint ("q", q)

  let dropRights :: (Ord a) => M.Map (Either a b) x -> M.Map a x
      dropRights xs = M.fromList [(b, x) | (Left b, x) <- M.toList xs]

  -- seems okay for concrete types
  pPrint ("lookupQS:", lookupQS q $ dropRights vpdM)

lookupQS :: (Ord a) => [NameQ] -> Map String (Map (Set Bool) (Set a)) -> Set a
lookupQS ns vpd =
  foldl (\result n -> lookupQ n vpd result) full $
    sortOn isNeg ns -- negatives last
  where
    full = S.unions $ vpd ^.. folded . folded
    isNeg (NameQ _ _ (Just (_, S.toList -> [x]))) = x
    isNeg _ = False

lookupQ ::
  (Ord a) =>
  -- | a single word like +A-
  NameQ ->
  Map String (Map (Set Bool) (Set a)) ->
  -- | modification of the result set
  (Set a -> Set a)
lookupQ NameQ {pol, name, pres} vpd = presOp pres $ S.unions (vpd ^.. ix name . polOp pol)
